name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
          cd src 
          dotnet restore
          dotnet tool restore
    - name: Build
      run: |
          cd src 
          dotnet build
          dotnet build 
    - name: Test
      run: |
          cd src 
          dotnet test

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: FileExtensions_RunTest_${{github.run_number}}
        path: src/TestFileExtensions/bin/Debug/net5.0/Reports
        retention-days: 1
          
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      run: |
        cd src
        dotnet coverlet TestFileExtensions\bin\Debug\net5.0\TestFileExtensions.dll --target "dotnet" --targetargs "test RecognizeFileExtension.sln --no-build"  --format opencover --exclude "[SampleWeb*]*"  --exclude "[xunit*]*" --verbosity detailed
        #dotnet coverlet TestFileExtensions\bin\Debug\net5.0\TestFileExtensions.dll --target "dotnet" --targetargs "test RecognizeFileExtension.sln"  --format opencover  --verbosity detailed
        dotnet reportgenerator "-reports:coverage.opencover.xml" "-targetdir:coveragereport" "-reporttypes:HTMLInline;HTMLSummary;Badges"


    - uses: codecov/codecov-action@v1
      with:
        files: src/coverage.opencover.xml 
        fail_ci_if_error: true # optional (default = false)
        #verbose: true # optional (default = false)
