name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
          cd src 
          dotnet restore
          dotnet tool restore
    - name: Build
      run: |
          cd src 
          dotnet build --no-restore
    - name: Test
      run: |
          cd src 
          dotnet test

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: RunTest_${{github.run_number}}
        path: src/TestFileExtensions/bin/Debug/net5.0/Reports
        retention-days: 1
          
